# Generated by Django 5.1.2 on 2024-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=5)),
                ('authorized_by', models.CharField(max_length=50)),
                ('qr_img_name', models.CharField(max_length=50)),
                ('pass_id', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
