# Generated by Django 5.1.2 on 2024-11-10 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_visitorpass_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 20, 44, 3, 598611, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='duration',
            field=models.CharField(max_length=5),
        ),
    ]
