# Generated by Django 5.1.2 on 2024-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_visitorpass_expire_at_alter_visitorpass_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorpass',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
