# Generated by Django 5.1.2 on 2024-11-23 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_visitorpass_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
