# Generated by Django 5.1.2 on 2024-11-24 11:48

import django.utils.timezone
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image_uploaded_at_alter_visitorpass_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorpass',
            options={'verbose_name_plural': 'Visitor Passes'},
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='created_at',
            field=models.DateTimeField(default=images.models.get_kolkata_time),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='expire_at',
            field=models.DateTimeField(default=images.models.get_kolkata_time),
        ),
    ]
