# Generated by Django 5.1.2 on 2024-11-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_visitorpass_options_visitorpass_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorpass',
            old_name='uuid',
            new_name='_encrypted_uuid',
        ),
    ]
